{{- define "aos.integration-job" -}}
{{- $hook := .hook -}}
{{- $integrations := .integrations -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: integration-duplo{{ if eq $hook "post-upgrade" }}-upgrade{{ end }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": {{ $hook }}
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: init-duplo
          image: "{{ .Values.integrationJob.image }}:{{ .Values.integrationJob.imageTag }}"
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for $DUPLO_AUTOMATION_DEPLOYMENT_NAME to be ready..."
              until curl --silent --fail --output /dev/null $DUPLO_AUTOMATION_ENDPOINT; do
                echo "Waiting for $DUPLO_AUTOMATION_ENDPOINT to be ready..."
                sleep 10
              done
              echo "Triggering Duplo automation integration..."
              INTEGRATIONS="{{ $integrations }}"
              for i in $INTEGRATIONS; do
                echo "Enabling $i"
                curl --fail --silent --show-error --location "$DUPLO_AUTOMATION_ENDPOINT/enable-integration" \
                  --header 'Content-Type:application/json' \
                  --data-raw "{\"integration_name\":\"$i\",\"context_name\":\"duplo-otel\"}" || { echo "❌ Failed to enable $i"; exit 1; }
              done
              echo "Enabling duplo-common"
              curl --fail --silent --show-error --location "$DUPLO_AUTOMATION_ENDPOINT/enable-integration" \
                --header 'Content-Type:application/json' \
                --data '{"integration_name":"duplo-common","context_name":"duplo-otel"}' || { echo "❌ Failed to enable duplo"; exit 1; }
              echo "✅ Duplo default provisioning completed successfully."
          env:
            - name: DUPLO_AUTOMATION_DEPLOYMENT_NAME
              value: "duplo-automation"
            - name: DUPLO_AUTOMATION_ENDPOINT
              value: "http://duplo-automation:5000"
      serviceAccountName: {{ $.Release.Namespace }}-edit-user
      restartPolicy: Never
{{- end -}} 