{{- if .Values.grafanaProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-proxy
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: {{ .Values.grafanaProxy.replicas }}
  selector:
    matchLabels:
      app: grafana-proxy
  template:
    metadata:
      labels:
        app: grafana-proxy
    spec:
      containers:
        - name: grafana-proxy
          image: "{{ .Values.grafanaProxy.image }}:{{ .Values.grafanaProxy.imageTag }}"
          ports:
            - name: proxy
              containerPort: 80
              protocol: TCP
          env:
            - name: DUPLO_AUTH_URL
              value: {{ .Values.global.duploAuthUrl | quote }}
            - name: BACKEND_URL
              value: "http://grafana-ui:3000"
            - name: CUSTOM_HEADER_ADD
              value: "proxy_set_header X-WEBAUTH-USER duplocloud;"
          readinessProbe:
            httpGet:
              path: /duplo_auth
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /duplo_auth
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
{{- toYaml .Values.grafanaProxy.resources | nindent 12 }}
{{- if .Values.grafanaProxy.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.grafanaProxy.nodeSelector | indent 8 }}
{{- end }}
{{- end }}