{{- if .Values.integrationJob.enabled }}
{{- include "aos.integration-job" (dict "hook" "post-install" "integrations" "apm linuxnode kubernetes slo aws-cloudwatch mimir loki tempo duplo-bootstrap" "Values" .Values "Release" .Release) }}
{{- end }} 