{{- if .Values.grafanaUI.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-ui-data
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafanaUI.volume.size }}
---
{{- end }}
{{- if .Values.duploAutomation.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duplo-automation-data
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.duploAutomation.volume.size }}
{{- end }} 