{{- if .Values.secrets.grafanaUI }}
apiVersion: v1
kind: Secret
metadata:
  name: grafanaui
  namespace: {{ .Values.global.tenantName }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secrets.grafanaUI.username | b64enc }}
  password: {{ .Values.secrets.grafanaUI.password | b64enc }}
---
{{- end }}
{{- if .Values.secrets.gpgPassphrase }}
apiVersion: v1
kind: Secret
metadata:
  name: gpg-passphrase
  namespace: {{ .Values.global.tenantName }}
type: Opaque
data:
  gpg_passphrase: {{ .Values.secrets.gpgPassphrase | b64enc }}
{{- end }} 