{{- if .Values.secrets.grafanaUI }}
apiVersion: v1
kind: Secret
metadata:
  name: grafanaui
  namespace: {{ $.Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.secrets.grafanaUI.username | b64enc }}
  password: {{ .Values.secrets.grafanaUI.password | b64enc }}
---
{{- end }}
{{- if .Values.secrets.gpgPassphrase }}
apiVersion: v1
kind: Secret
metadata:
  name: gpg-passphrase
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  gpg_passphrase: {{ .Values.secrets.gpgPassphrase | b64enc }}
{{- end }}
{{- if .Values.grafanaUI.pdc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-pdc-agent
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  cluster: {{ .Values.grafanaUI.pdc.config.pdc_cluster | b64enc }}
  hosted-grafana-id: {{ .Values.grafanaUI.pdc.config.gc_instance_id | b64enc }}
  token: {{ .Values.grafanaUI.pdc.config.pdc_token | b64enc }}
{{- end }} 