{{- if and .Values.grafanaUI.enabled (ne (.Values.global.stackType | default "main") "collector") }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-ui
spec:
  selector:
    app: grafana-ui
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
---
{{- end }}
{{- if and .Values.duploAutomation.enabled (ne (.Values.global.stackType | default "main") "collector") }}
apiVersion: v1
kind: Service
metadata:
  name: duplo-automation
  namespace: {{ $.Release.Namespace }}
  labels:
    app: duplo-automation
spec:
  selector:
    app: duplo-automation
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
---
{{- end }}
{{- if and .Values.grafanaProxy.enabled (ne (.Values.global.stackType | default "main") "collector") }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-proxy
spec:
  selector:
    app: grafana-proxy
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
      protocol: TCP
{{- end }} 