{{- if .Values.grafanaUI.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-ui
spec:
  selector:
    app: grafana-ui
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
---
{{- end }}
{{- if .Values.duploAutomation.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: duplo-automation
  namespace: {{ $.Release.Namespace }}
  labels:
    app: duplo-automation
spec:
  selector:
    app: duplo-automation
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
---
{{- end }}
{{- if .Values.grafanaProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-proxy
spec:
  selector:
    app: grafana-proxy
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
      protocol: TCP
---
{{- end }}
{{- if .Values.grafanaMCP.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcp-server
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-mcp-server
spec:
  selector:
    app: grafana-mcp-server
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
{{- end }}
{{- if and .Values.grafanaMCP.enabled .Values.grafanaMCP.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcp-proxy
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-mcp-proxy
spec:
  selector:
    app: grafana-mcp-proxy
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
      protocol: TCP
{{- end }}