{{- if .Values.grafanaUI.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana-ui
  namespace: {{ $.Release.Namespace }}
  labels:
    app: grafana-ui
spec:
  replicas: {{ .Values.grafanaUI.replicas }}
  selector:
    matchLabels:
      app: grafana-ui
  serviceName: grafana-ui
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: grafana-ui
      annotations:
        k8s_grafana_com_scrape: "true"
        k8s_grafana_com_job: "grafana-metrics"
        k8s_grafana_com_metrics_path: "/metrics"
        k8s_grafana_com_metrics_portNumber: "3000"
    spec:
      {{ if .Values.grafanaUI.syntheticMonitoring.enabled }}
      volumes:
        - name: synthetic-monitoring-datasource
          configMap:
            name: grafana-provisioning-synthetic-monitoring
        - name: synthetic-monitoring-plugin
          configMap:
            name: grafana-provisioning-synthetic-monitoring
      {{ end }}
      containers:
        - name: grafana-ui
          image: "{{ .Values.grafanaUI.image }}:{{ .Values.grafanaUI.imageTag | default .Values.global.release }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_INSTALL_PLUGINS
              value: {{ if .Values.grafanaUI.syntheticMonitoring.enabled }}{{ printf "%s,%s" .Values.grafanaUI.plugins "grafana-synthetic-monitoring-app" | quote }}{{ else }}{{ .Values.grafanaUI.plugins | quote }}{{ end }}
            - name: GF_SERVER_ROOT_URL
              value: "{{ .Values.global.grafanaProxyUrl }}"
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafanaui
                  key: username
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafanaui
                  key: password
          {{- if .Values.grafanaUI.smtp.enabled }}
            - name: GF_SMTP_ENABLED
              value: 'true'
            - name: GF_SMTP_HOST
              value: value: {{ printf "%s:%s" .Values.grafanaUI.smtp.config.host .Values.grafanaUI.smtp.config.port | quote }}
            - name: GF_SMTP_STARTTLS_POLICY
              value: {{ .Values.grafanaUI.smtp.config.starttlsPolicy | quote }}
            - name: GF_SMTP_SKIP_VERIFY
              value: 'true'
            - name: GF_SMTP_FROM_ADDRESS
              value: {{ .Values.grafanaUI.smtp.config.fromAddress | quote }}
            - name: GF_SMTP_FROM_NAME
              value: {{ .Values.grafanaUI.smtp.config.fromName | quote }}
            - name: GF_SMTP_USER
              value: {{ .Values.grafanaUI.smtp.config.username | quote }}
            - name: GF_SMTP_PASSWORD
              value: {{ .Values.grafanaUI.smtp.config.password | quote }}
          {{- end }}
          {{- with .Values.grafanaUI.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.grafanaUI.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/grafana
            {{- if .Values.grafanaUI.syntheticMonitoring.enabled }}
            - name: synthetic-monitoring-plugin
              mountPath: /etc/grafana/provisioning/plugins/grafanacloud-synthetic-monitoring.yml
              subPath: grafanacloud-synthetic-monitoring.yml
            - name: synthetic-monitoring-datasource
              mountPath: /etc/grafana/provisioning/datasources/grafanacloud.yml
              subPath: grafanacloud.yml
          {{- end }}
      securityContext:
        fsGroup: 472
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: grafana-ui
                topologyKey: kubernetes.io/hostname
{{- if .Values.grafanaUI.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.grafanaUI.nodeSelector | indent 8 }}
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.grafanaUI.volume.size }}
---
{{- end }}
{{- if .Values.duploAutomation.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: duplo-automation
  namespace: {{ $.Release.Namespace }}
  labels:
    app: duplo-automation
spec:
  replicas: {{ .Values.duploAutomation.replicas }}
  selector:
    matchLabels:
      app: duplo-automation
  serviceName: duplo-automation
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  template:
    metadata:
      labels:
        app: duplo-automation
    spec:
      containers:
        - name: duplo-automation
          image: "{{ .Values.duploAutomation.image }}:{{ .Values.duploAutomation.imageTag | default .Values.global.release }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: GRR_GRAFANA_URL
              value: "http://grafana-ui:3000"
            - name: GRR_GRAFANA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafanaui
                  key: password
            - name: GRR_GRAFANA_USER
              valueFrom:
                secretKeyRef:
                  name: grafanaui
                  key: username
            - name: GRR_MIMIR_ADDRESS
              value: "http://duplo-metrics-ruler:8080"
            - name: GRR_MIMIR_TENANT_ID
              value: "anonymous"
            - name: GRR_TARGETS
              value: "Datasource,DashboardFolder,LibraryElement,Dashboard,AlertRuleGroup,AlertNotificationPolicy,AlertContactPoint,PrometheusRuleGroup"
            - name: GRR_OUTPUT_FORMAT
              value: "yaml"
            - name: GRR_ONLY_SPEC
              value: "false"
            - name: GRIZZLY_HTTP_TIMEOUT
              value: "60"
            - name: MIMIR_RULER
              value: "http://duplo-metrics-ruler:8080"
            - name: MIMIR_ADDRESS
              value: "http://duplo-metrics-nginx"
            - name: MIMIR_ALERTMANAGER
              value: "http://duplo-metrics-alertmanager:8080"
            - name: MIMIR_TENANT_ID
              value: "anonymous"
            - name: ONCALL_WEBHOOK_URL
              value: "{{ .Values.global.oncallWebhookUrl }}"
            - name: CUSTOMER_NAME
              value: "{{ .Values.global.customerName }}"
            - name: DEPLOYMENT_NAME
              value: "{{ .Values.global.clusterName }}"
            - name: ENVIRONMENT
              value: "{{ .Values.global.environment }}"
            - name: AOS_GRAFANA_URL
              value: "{{ .Values.global.grafanaProxyUrl }}"
            - name: AOS_SLACK_WEBHOOK
              value: "{{ .Values.global.slackWebhookUrl }}"
            - name: AOS_SLACK_CHANNEL_NAME
              value: "duplo-otel-alerting"
            - name: AOS_AUTOMATION_WEBHOOK
              value: "{{ .Values.global.automationWebhookUrl }}"
            - name: AOS_DUPLO_PORTAL_NAME
              value: "{{ .Values.global.customerName }}-{{ .Values.global.environment }}"
            - name: AOS_NAMESPACE_FILTER
              value: "{{ .Values.global.namespaceFilter }}"
          {{- with .Values.duploAutomation.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.aiSuite.enabled }}
            - name: AI_SUITE_ENABLED
              value: "true"
            - name: AI_SUITE_DUPLO_HOST
              valueFrom:
                secretKeyRef:
                  name: duplo-automation
                  key: duplo_host
            - name: AI_SUITE_DUPLO_DEFAULT_TENANT
              valueFrom:
                secretKeyRef:
                  name: duplo-automation
                  key: duplo_default_tenant
            - name: AI_SUITE_DUPLO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: duplo-automation
                  key: duplo_token
            - name: AI_SUITE_INSTANCE_ID
              value: "{{ .Values.aiSuite.agent_instance_id }}"
            - name: AI_SUITE_AGENT_NAME
              value: "{{ .Values.aiSuite.agent_name }}"
          {{- else }}
            - name: AI_SUITE_ENABLED
              value: "false"
          {{- end }}
          {{- if eq .Values.global.cloud "aws" }}
            - name: AOS_REGION
              value: "{{ .Values.global.AOSRegion }}"
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /app/data
      securityContext:
        fsGroup: 472
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: duplo-automation
                topologyKey: kubernetes.io/hostname
{{- if .Values.duploAutomation.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.duploAutomation.nodeSelector | indent 8 }}
{{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.duploAutomation.volume.size }}
---
{{- end }} 