name: Release Charts

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger  

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "srikarduplo"
          git config user.email "srikar@duplocloud.net"

      - name: Update Chart.yaml version
        run: |
          CHART_FILE="charts/aos/Chart.yaml"
          # Get the release tag and remove the 'v' prefix if it exists
          RELEASE_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          
          # Update version in Chart.yaml
          sed -i "s/^version: .*/version: $RELEASE_VERSION/" $CHART_FILE
          
          echo "Updated $CHART_FILE to version $RELEASE_VERSION"

      - name: Commit and push Chart.yaml changes
        run: |
          git add charts/aos/Chart.yaml
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update chart version to ${{ github.ref_name }}"
            git push
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"